"""
generate_excel_report.py - Excel MIS Dashboard Generator
Reads cleaned data and generates a professional multi-sheet Excel report using openpyxl.
"""
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.utils import get_column_letter
from datetime import datetime
from pathlib import Path

# --- Constants & Styles ---
HEADER_FILL = PatternFill(start_color="1F3864", end_color="1F3864", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True)
ALT_FILL_1 = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")
ALT_FILL_2 = PatternFill(start_color="EBF3FB", end_color="EBF3FB", fill_type="solid")
THIN_BORDER = Border(left=Side(style='thin'), right=Side(style='thin'), top=Side(style='thin'), bottom=Side(style='thin'))
CURRENCY_FORMAT = '[$₹-en-IN]#,##0;-[$₹-en-IN]#,##0;-'
PCT_FORMAT = '0.0%'

def apply_table_style(ws, start_row, start_col, num_rows, num_cols, has_header=True):
    for r in range(start_row, start_row + num_rows):
        is_header = has_header and r == start_row
        bg_fill = HEADER_FILL if is_header else (ALT_FILL_1 if r % 2 == 0 else ALT_FILL_2)
        font = HEADER_FONT if is_header else Font()
        
        for c in range(start_col, start_col + num_cols):
            cell = ws.cell(row=r, column=c)
            cell.fill = bg_fill
            cell.font = font
            cell.border = THIN_BORDER

def auto_adjust_cols(ws):
    for col in ws.columns:
        max_length = 0
        column = col[0].column_letter
        for cell in col:
            try:
                if cell.value:
                    if len(str(cell.value)) > max_length:
                        max_length = len(str(cell.value))
            except:
                pass
        adjusted_width = (max_length + 2)
        ws.column_dimensions[column].width = min(adjusted_width, 40)

def set_footer(ws):
    ws.oddFooter.center.text = "Generated by MIS Dashboard Pipeline | Confidential"
    ws.evenFooter.center.text = "Generated by MIS Dashboard Pipeline | Confidential"

def generate_report():
    input_path = Path("data/cleaned/clinic_cleaned_data.csv")
    output_path = Path("output/MIS_Weekly_Report.xlsx")
    
    if not input_path.exists():
        print(f"❌ Error: Could not find '{input_path}'")
        return
        
    df = pd.read_csv(input_path)
    
    wb = Workbook()
    
    # Remove default sheet
    wb.remove(wb.active)
    
    # ---------------------------------------------------------
    # SHEET 1: Executive Summary
    # ---------------------------------------------------------
    ws1 = wb.create_sheet("Executive Summary")
    ws1.merge_cells('B2:E2')
    ws1['B2'] = "Mental Health Clinic — MIS Dashboard Report"
    ws1['B2'].font = Font(size=18, bold=True, color="1F3864")
    ws1['B2'].alignment = Alignment(horizontal='center')
    
    ws1.merge_cells('B3:E3')
    ws1['B3'] = f"Report Generation Date: {datetime.now().strftime('%Y-%m-%d')}"
    ws1['B3'].font = Font(italic=True)
    ws1['B3'].alignment = Alignment(horizontal='center')
    
    # Calculations
    total_apps = len(df)
    total_rev = df['revenue'].sum()
    attendance_rate = df['attended'].mean()
    avg_sat = df['satisfaction_score'].mean()
    avg_wait = df['wait_time_days'].mean()
    most_active_dept = df['department'].value_counts().idxmax()
    top_therapist = df['therapist_name'].value_counts().idxmax()
    
    kpis = [
        ("Total Appointments (2023–2024)", total_apps, '#,##0'),
        ("Total Revenue Collected (INR)", total_rev, CURRENCY_FORMAT),
        ("Overall Attendance Rate (%)", attendance_rate, PCT_FORMAT),
        ("Average Satisfaction Score", avg_sat, '0.0'),
        ("Average Wait Time (days)", avg_wait, '0.0'),
        ("Most Active Department", most_active_dept, None),
        ("Top Performing Therapist", top_therapist, None)
    ]
    
    ws1['B5'] = "Key Performance Indicator"
    ws1['C5'] = "Value"
    
    for i, (metric, value, num_fmt) in enumerate(kpis):
        r = 6 + i
        ws1.cell(row=r, column=2, value=metric)
        c_val = ws1.cell(row=r, column=3, value=value)
        if num_fmt:
            c_val.number_format = num_fmt
    
    apply_table_style(ws1, 5, 2, len(kpis) + 1, 2)
    auto_adjust_cols(ws1)
    set_footer(ws1)
    
    # ---------------------------------------------------------
    # SHEET 2: Monthly Trend
    # ---------------------------------------------------------
    ws2 = wb.create_sheet("Monthly Trend")
    
    trend = df.groupby(['year', 'month_num', 'month']).agg(
        Appts=('patient_id', 'count'),
        Rev=('revenue', 'sum'),
        AttRate=('attended', 'mean')
    ).reset_index()
    
    pivot = trend.pivot(index=['month_num', 'month'], columns='year', values=['Appts', 'Rev', 'AttRate'])
    
    pivot_cols = []
    for col in pivot.columns:
        pivot_cols.append(f"{col[0]}_{col[1]}")
    pivot.columns = pivot_cols
    pivot = pivot.reset_index().sort_values('month_num').drop(columns=['month_num'])
    
    headers = ["Month"] + pivot.columns[1:].tolist()
    for c, h in enumerate(headers, 1):
        ws2.cell(row=2, column=c, value=h)
        
    for r, row in enumerate(dataframe_to_rows(pivot, index=False, header=False), 3):
        for c, val in enumerate(row, 1):
            cell = ws2.cell(row=r, column=c, value=val)
            header = headers[c-1]
            if "Rev" in header:
                cell.number_format = CURRENCY_FORMAT
            elif "AttRate" in header:
                cell.number_format = PCT_FORMAT
            
            # Conditional formatting: < 80% attendance
            if "AttRate" in header and val is not None and val < 0.8:
                cell.fill = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
                cell.font = Font(color="9C0006")
                
    # Totals Row
    last_row = 3 + len(pivot)
    ws2.cell(row=last_row, column=1, value="Grand Total").font = Font(bold=True)
    for c in range(2, len(headers) + 1):
        col_letter = get_column_letter(c)
        if "AttRate" in headers[c-1]:
            ws2.cell(row=last_row, column=c, value=f"=AVERAGE({col_letter}3:{col_letter}{last_row-1})").number_format = PCT_FORMAT
        else:
            ws2.cell(row=last_row, column=c, value=f"=SUM({col_letter}3:{col_letter}{last_row-1})")
            if "Rev" in headers[c-1]: ws2.cell(row=last_row, column=c).number_format = CURRENCY_FORMAT
            
    apply_table_style(ws2, 2, 1, len(pivot) + 2, len(headers))
    
    # VLOOKUP-style reference
    ws2.cell(row=2, column=len(headers)+2, value="Therapist ID")
    ws2.cell(row=2, column=len(headers)+3, value="Therapist Name")
    unique_therapists = df[['therapist_id', 'therapist_name']].drop_duplicates().sort_values('therapist_id')
    for r, row in enumerate(dataframe_to_rows(unique_therapists, index=False, header=False), 3):
        ws2.cell(row=r, column=len(headers)+2, value=row[0])
        ws2.cell(row=r, column=len(headers)+3, value=row[1])
    apply_table_style(ws2, 2, len(headers)+2, len(unique_therapists)+1, 2)
    
    auto_adjust_cols(ws2)
    set_footer(ws2)
    
    # ---------------------------------------------------------
    # SHEET 3: Department Analysis
    # ---------------------------------------------------------
    ws3 = wb.create_sheet("Department Analysis")
    dept = df.groupby('department').agg(
        Total_Appointments=('patient_id', 'count'),
        Attended=('attended', 'sum'),
        Attendance_Rate=('attended', 'mean'),
        Avg_Satisfaction=('satisfaction_score', 'mean'),
        Total_Revenue=('revenue', 'sum'),
        Avg_Wait_Time=('wait_time_days', 'mean')
    ).reset_index().sort_values('Total_Appointments', ascending=False)
    
    headers = ["Department", "Total Appointments", "Attended", "Attendance Rate (%)", "Avg Satisfaction", "Total Revenue", "Avg Wait Time"]
    for c, h in enumerate(headers, 1):
        ws3.cell(row=2, column=c, value=h)
        
    for r, row in enumerate(dataframe_to_rows(dept, index=False, header=False), 3):
        for c, val in enumerate(row, 1):
            cell = ws3.cell(row=r, column=c, value=val)
            if c == 4: cell.number_format = PCT_FORMAT
            elif c == 5 or c == 7: cell.number_format = '0.0'
            elif c == 6: cell.number_format = CURRENCY_FORMAT
            
            if r == 3: cell.font = Font(bold=True)
                
    apply_table_style(ws3, 2, 1, len(dept) + 1, len(headers))
    auto_adjust_cols(ws3)
    set_footer(ws3)
    
    # ---------------------------------------------------------
    # SHEET 4: Therapist Performance
    # ---------------------------------------------------------
    ws4 = wb.create_sheet("Therapist Performance")
    
    def crisis_count(x):
        return (x == 'Crisis Intervention').sum()
        
    thera = df.groupby(['therapist_name', 'therapist_id', 'department']).agg(
        Total_Sessions=('patient_id', 'count'),
        Attendance_Rate=('attended', 'mean'),
        Avg_Satisfaction=('satisfaction_score', 'mean'),
        Total_Revenue=('revenue', 'sum'),
        Crisis_Handled=('appointment_type', crisis_count)
    ).reset_index()
    
    def perf_band(sat):
        if pd.isna(sat): return "N/A"
        if sat > 4.0: return "High"
        if sat >= 3.0: return "Medium"
        return "Needs Improvement"
        
    thera['Performance_Band'] = thera['Avg_Satisfaction'].apply(perf_band)
    
    headers = ["Therapist Name", "ID", "Department", "Total Sessions", "Attendance Rate (%)", "Avg Satisfaction", "Total Revenue Generated", "Crisis Sessions Handled", "Performance Band"]
    for c, h in enumerate(headers, 1):
        ws4.cell(row=2, column=c, value=h)
        
    for r, row in enumerate(dataframe_to_rows(thera, index=False, header=False), 3):
        for c, val in enumerate(row, 1):
            cell = ws4.cell(row=r, column=c, value=val)
            if c == 5: cell.number_format = PCT_FORMAT
            elif c == 6: cell.number_format = '0.0'
            elif c == 7: cell.number_format = CURRENCY_FORMAT
            
            if c == 9: 
                if val == "High":
                    cell.fill = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
                    cell.font = Font(color="006100")
                elif val == "Medium":
                    cell.fill = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")
                    cell.font = Font(color="9C5700")
                elif val == "Needs Improvement":
                    cell.fill = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
                    cell.font = Font(color="9C0006")
                    
    apply_table_style(ws4, 2, 1, len(thera) + 1, len(headers))
    auto_adjust_cols(ws4)
    set_footer(ws4)
    
    # ---------------------------------------------------------
    # SHEET 5: City & Referral Breakdown
    # ---------------------------------------------------------
    ws5 = wb.create_sheet("City & Referral Breakdown")
    
    city_stats = df.groupby('city').agg(Appts=('patient_id', 'count'), Revenue=('revenue', 'sum')).reset_index()
    ref_stats = df.groupby('referral_source').agg(Appts=('patient_id', 'count')).reset_index()
    ref_stats['Share'] = ref_stats['Appts'] / ref_stats['Appts'].sum()
    
    ws5.cell(row=2, column=2, value="City")
    ws5.cell(row=2, column=3, value="Appointments")
    ws5.cell(row=2, column=4, value="Revenue")
    for r, row in enumerate(dataframe_to_rows(city_stats, index=False, header=False), 3):
        for c, val in enumerate(row, 2):
            cell = ws5.cell(row=r, column=c, value=val)
            if c == 4: cell.number_format = CURRENCY_FORMAT
    apply_table_style(ws5, 2, 2, len(city_stats) + 1, 3)
    
    ws5.cell(row=2, column=6, value="Referral Source")
    ws5.cell(row=2, column=7, value="Appointments")
    ws5.cell(row=2, column=8, value="Share (%)")
    for r, row in enumerate(dataframe_to_rows(ref_stats, index=False, header=False), 3):
        for c, val in enumerate(row, 6):
            cell = ws5.cell(row=r, column=c, value=val)
            if c == 8: cell.number_format = PCT_FORMAT
    apply_table_style(ws5, 2, 6, len(ref_stats) + 1, 3)
    
    auto_adjust_cols(ws5)
    set_footer(ws5)
    
    # ---------------------------------------------------------
    # SHEET 6: Raw Data (Cleaned)
    # ---------------------------------------------------------
    ws6 = wb.create_sheet("Raw Data (Cleaned)")
    for r, row in enumerate(dataframe_to_rows(df, index=False, header=True), 1):
        for c, val in enumerate(row, 1):
            ws6.cell(row=r, column=c, value=val)
            
    apply_table_style(ws6, 1, 1, 1, len(df.columns))
    
    for r in range(2, len(df) + 2):
        bg = ALT_FILL_1 if r % 2 == 0 else ALT_FILL_2
        for c in range(1, len(df.columns) + 1):
            cell = ws6.cell(row=r, column=c)
            cell.fill = bg
            if 'fee' in df.columns[c-1].lower() or 'revenue' in df.columns[c-1].lower():
                cell.number_format = CURRENCY_FORMAT
                
    ws6.auto_filter.ref = ws6.dimensions
    ws6.freeze_panes = "A2"
    
    auto_adjust_cols(ws6)
    set_footer(ws6)
    
    try:
        wb.save(output_path)
        print(f"✅ Saved Excel MIS Report to -> {output_path}")
    except PermissionError:
        print(f"❌ Error: Permission denied. Make sure '{output_path}' is closed.")

if __name__ == "__main__":
    generate_report()
